version: '3.2'
services:
  web:
    build: .
    ports:
      - "8015:80"
    depends_on:
      - database
    environment:
      APP_ENV: dev
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: "serverName=Backend"
    volumes:
      - ./:/var/www/html
    container_name: virtual_meeting_web
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: virtual_meeting
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3315:3306"
    container_name: virtual_meeting_db